language: node_js
node_js:
  - "node"
  - "lts/*"
jobs:
  include:
    - stage: test
      script: npm run build && npm run prepush
    - stage: coverage
      script: jest --coverage --coverageReporters=text-lcov | coveralls
